### ISSUE TITLE
关于checker.py的一个疑问

### ISSUE THREAD

**Issue by Danielshara** [SeanLee97/xmnlp#10]
```
    def calc_proba(self, gram):
        x = self.bi[tuple(gram)]
        y = self.uni[gram[0]]
        return float((x + 1)) / (y + len(self.uni.keys())**2)
```
这段代码的作用是smoothing吧?为什么是用y + len(self.uni.keys())**2而不是y + len(self.uni.keys())呢?

**Comment by SeanLee97** [comment]
您好，0.1.8版本已经发布，[新版本特性](https://github.com/SeanLee97/xmnlp/releases)

0.1.7版本的checker已经被弃用了，0.1.8的checker主要完成词级别的拼写检查，基于symspell算法开发。
整句的文本纠错我会以独立的模块开放，是基于神经网络的，欢迎关注。
