### ISSUE TITLE
java版的包哪里可以下载到？

### ISSUE THREAD

**Issue by LBJ-Software** [SeanLee97/xmnlp#13]
我看到java项目文件中有人用到1.4版本的xmnlp包，可是maven公仓以及百度谷歌都搜不到这个包，请问哪里可以找到呢。

**Comment by SeanLee97** [comment]
@LBJ-Software 您好，我记得 github 中有同名的 repo 是 java 编写的，可能本 repo 不是你所指的哦。目前 xmnlp 尚未支持 java  。

**Comment by LBJ-Software** [comment]
> @LBJ-Software 您好，我记得 github 中有同名的 repo 是 java 编写的，可能本 repo 不是你所指的哦。目前 xmnlp 尚未支持 java 。
