### ISSUE TITLE
关于特殊名词

### ISSUE THREAD

**Issue by dwbaron** [SeanLee97/xmnlp#17]
类似债券简称，比如“02进出04”，特殊名词比如“5G”，我发现在分词的时候会打散

**Comment by SeanLee97** [comment]
Thanks for your suggestions, we will fix the problem that can not detect proper noun formed by digital and  English alphabet.

**Comment by dwbaron** [comment]
I tried to combined trie (which perform the exactly match) and hmm seg to fix such problem temporarily.

**Comment by dwbaron** [comment]
it seems that u first use zh-char to split the sentence,  use eng-char seems better?

**Comment by dwbaron** [comment]
![image](https://user-images.githubusercontent.com/23231223/57193800-e544f500-6f71-11e9-9016-296d33cc73d1.png)
I try to figure out this en-char problems follow my above solution

**Comment by SeanLee97** [comment]
Thanks for your suggestions! I will fix the problem when I free. If you are willing to give contributions to this repo, you can create a PR! Look forward to your contributions!
