### ISSUE TITLE
checker用的什么模型？

### ISSUE THREAD

**Issue by noletter** [SeanLee97/xmnlp#28]
能简要介绍一下检测和纠错的模型思路吗

**Comment by SeanLee97** [comment]
思路还是挺简单的，大概如下：

1. 检测：对人民日报语料的句子随机采样词来替换成错误的词，替换方式目前有两种：1) 同音词替换  2) 形近字替换，记录下错词位置，然后通过建模来预测错词位置。
2. 纠错：对于识别出错词的位置进行 [MASK] 然后预测 [MASK] 处可能的词，最后通过拼音来排序。

最近在搞新的版本，新版本会增加新的词替换方式，会把检测和纠错合并。

Stay tuned:)

**Comment by noletter** [comment]
> 思路还是挺简单的，大概如下：
> 
> 1. 检测：对人民日报语料的句子随机采样词来替换成错误的词，替换方式目前有两种：1) 同音词替换  2) 形近字替换，记录下错词位置，然后通过建模来预测错词位置。
> 2. 纠错：对于识别出错词的位置进行 [MASK] 然后预测 [MASK] 处可能的词，最后通过拼音来排序。
> 
> 最近在搞新的版本，新版本会增加新的词替换方式，会把检测和纠错合并。
> 
> Stay tuned:)

非常感谢你及时的回复。
另外：
    1. 我这边关注了你们的公众号，无法进到NLP交流群，貌似微信公众号有一些问题，无法显示交流群的菜单
    2. 我目前在做纠错也是这个流程，检错标签，转换[MASK]用MLM模型进行预测，感觉比较棘手的是数据层面，希望能得到和你的微信沟通方式，或者是微信群。
