### ISSUE TITLE
缩短纠错时间

### ISSUE THREAD

**Issue by 1394125422** [SeanLee97/xmnlp#3]
您好，您的代码对我最近做的拼音纠错有很大帮助，拼音纠错的效果非常好，非常感谢你的分享，但是，我想把时间缩短到200ms，您有什么建议吗？

**Comment by SeanLee97** [comment]
的确存在复杂度过高的问题，目前暂时还没想到较优化的算法。不过有些地方我认为是可以改进的，比如说编辑距离采用动态规划来实现，可以降低复杂度。
如果您有好的算法，欢迎 pr 哦！

**Comment by SeanLee97** [comment]
您好，0.1.8版本已经发布，[新版本特性](https://github.com/SeanLee97/xmnlp/releases/tag/v0.1.8)

0.1.7版本的checker已经被弃用了，0.1.8的checker主要完成词级别的拼写检查，基于symspell算法开发。
整句的文本纠错我会以独立的模块开放，是基于神经网络的，欢迎关注。
