### ISSUE TITLE
代码勘误

### ISSUE THREAD

**Issue by ZXTFINAL** [SeanLee97/xmnlp#30]
base_model.py内对onnxruntime调用代码有误

`# -*- coding: utf-8 -*-

from abc import ABCMeta, abstractmethod

import onnxruntime as ort

class BaseModel(metaclass=ABCMeta):

    def __init__(self, model_path: str):
        self.sess = ort.InferenceSession(model_path, providors=['CPUExecutionProvider'])

    @abstractmethod
    def predict(self):
        raise NotImplementedError`

是providers不是providors

**Comment by SeanLee97** [comment]
已修复
