### ISSUE TITLE
Original error was: PyCapsule_Import could not import module "datetime"

### ISSUE THREAD

**Issue by atpwolf** [SeanLee97/xmnlp#34]
请问一下这是什么问题？放在win7就只能UserWarning: Unsupported Windows version (7). ONNX Runtime supports Windows 10 and above, only.
  warnings.warn('Unsupported Windows version (%s). ONNX Runtime supports Windows 10 and above, only.' %
Lazy load checker...

但放到win10就变成以下这样了。

__init__.py 22 <module>
from . import multiarray

multiarray.py 12 <module>
from . import overrides

overrides.py 7 <module>
from numpy.core._multiarray_umath import (

ImportError:
PyCapsule_Import could not import module "datetime"

---------------------------------------------------------------------------------------------------------------------------------------------------------
xmnlp测试.py 1 <module>
import xmnlp

__init__.py 15 <module>
from xmnlp import config

__init__.py 6 <module>
from xmnlp.utils import load_stopword

__init__.py 12 <module>
import numpy as np

__init__.py 140 <module>
from . import core

__init__.py 48 <module>
raise ImportError(msg)

ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "D:\LLD\python3\python.exe"
  * The NumPy version is: "1.19.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: PyCapsule_Import could not import module "datetime"

**Comment by SeanLee97** [comment]
这可能是 onnxruntime 版本的问题，新版本 xmnlp 已经锁定 onnxruntime 的版本，可以重新试一下。如果在 windows 下还不 work 我暂时也没有解决方法，另外 onnxruntime 是微软维护的，按理说 windows 是安装是没问题的
