### ISSUE TITLE
情感分析

### ISSUE THREAD

**Issue by carrotshub** [SeanLee97/xmnlp#4]
非常感谢您的分享，正在学习这个项目，对情感分析很感兴趣。有点困惑想请教一下，您在做情感分析时是采用什么方法做的特征选择呢？最终计算得到的情感数值是根据什么计算得到的呢？再次感谢~还有您这个项目有没有学习交流的QQ群之类的呢？

**Comment by SeanLee97** [comment]
1. 情感分析目前采用了朴素贝叶斯来实现
2. 情感值和输出的概率挂钩，对于正类直接返回概率值probability，对于负类返回 1 - probability, 具体的计算公式可以参见 ： [nbayes.py](https://github.com/SeanLee97/xmnlp/blob/master/xmnlp/utils/clf/nbayes.py)
3. 目前还没考虑建交流群

**Comment by carrotshub** [comment]
好的~谢谢您。再次叨扰下您，在训练NB分类器时，您的特征是采用哪种机制提取的呢？基于情感词典还是TF-IDF？或者其他方法。。

**Comment by SeanLee97** [comment]
您好，0.1.8版本已经发布，[新版本特性](https://github.com/SeanLee97/xmnlp/releases/tag/v0.1.8)

0.1.7版本的checker已经被弃用了，0.1.8的checker主要完成词级别的拼写检查，基于symspell算法开发。
整句的文本纠错我会以独立的模块开放，是基于神经网络的，欢迎关注。
