### ISSUE TITLE
纠错字典表

### ISSUE THREAD

**Issue by Garrybest** [SeanLee97/xmnlp#5]
您好，这个工具对我很有帮助，非常感谢您的分享。我对纠错功能很感兴趣，请问纠错可以自己设置一些非登陆词的字典表吗？我在使用过程中发现某些专有的特殊词汇会被错误地改正。

**Comment by SeanLee97** [comment]
您好，目前暂不支持专有词汇，您有好的想法的话欢迎分享。

**Comment by SeanLee97** [comment]
您好，0.1.8版本已经发布，[新版本特性](https://github.com/SeanLee97/xmnlp/releases/tag/v0.1.8)

0.1.7版本的checker已经被弃用了，0.1.8的checker主要完成词级别的拼写检查，基于symspell算法开发。
整句的文本纠错我会以独立的模块开放，是基于神经网络的，欢迎关注。

**Comment by MrRace** [comment]
所以，其实纠错的时候，没有必要加载userdict.txt这个字典表吧？该纠错功能好像不支持自定义的名词纠错？
