### ISSUE TITLE
文本纠错

### ISSUE THREAD

**Issue by cloudfool** [SeanLee97/xmnlp#6]
你好，

我想问一下，这个文本纠错的功能是只能将一个字换成另一个字么？对于少字，多字的错误可以解决么？

**Comment by SeanLee97** [comment]
下一个版本会做相应的更新

**Comment by SeanLee97** [comment]
您好，0.1.8版本已经发布，[新版本特性](https://github.com/SeanLee97/xmnlp/releases/tag/v0.1.8)

0.1.7版本的checker已经被弃用了，0.1.8的checker主要完成词级别的拼写检查，基于symspell算法开发。
整句的文本纠错我会以独立的模块开放，是基于神经网络的，欢迎关注。
