### ISSUE TITLE
python3 userdict.txt 加载错误

### ISSUE THREAD

**Issue by liutianfang** [SeanLee97/xmnlp#7]
我的环境：win10中文版，python3.6

examples的错误信息

    UnicodeDecodeError: 'gbk' codec can't decode byte 0xaa in position 35: illegal multibyte sequence

我的修复：
dag.py line 159:  with open(fname, 'r',encoding='utf-8') as f:

**Comment by SeanLee97** [comment]
@liutianfang 由于没在windows下测试，所以不保证兼容，下一版本会兼容windows

**Comment by Sniper970119** [comment]
加个mode 和 encoding 属性就行

**Comment by SeanLee97** [comment]
您好，0.1.8版本已经发布，[新版本特性](https://github.com/SeanLee97/xmnlp/releases/tag/v0.1.8)

新版本已经支持了windows.
