### ISSUE TITLE
分词及userdict的格式

### ISSUE THREAD

**Issue by liutianfang** [SeanLee97/xmnlp#8]
分词j结果：
记住钥匙放在厨房餐桌上  ->记住 / 钥匙 / 放在 / 厨房 / 餐桌上
"记住钥匙放在厨房桌子上" ->记住 / 钥匙 / 放在 / 厨房 / 桌子 / 上

应该是餐桌没有在字典中。我在examples中的userdict增加了餐桌也没有用，如何增加字典值，词后面的5 nw是什么意思，都有哪些选择

人工智能 5 nw
机器学习 5

**Comment by SeanLee97** [comment]
@liutianfang 自定义词典的格式:
词 词频 词性

像您的这种情况建议增大词频
